# Generated by Django 5.1.1 on 2024-10-17 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockprice", name="date", field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="stockprice",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="stocks.stocksymbol",
            ),
        ),
        migrations.AlterField(
            model_name="stocksymbol",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="PortfolioEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shares", models.FloatField()),
                ("price", models.FloatField()),
                ("avg_cost", models.FloatField()),
                ("total_return", models.FloatField()),
                ("equity", models.FloatField()),
                ("gain_since_invested", models.FloatField()),
                ("allocation", models.FloatField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stocksymbol",
                    ),
                ),
            ],
        ),
    ]
